# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('url', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('static_id', models.CharField(default='unknown.png', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.Icon'),
        ),
    ]
