# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20160831_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Icon'),
        ),
    ]
