# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20160831_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Item'),
        ),
    ]
