# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20160901_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_purchase_from_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
