# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_item_can_purchase_from_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylisting',
            name='for_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Item'),
        ),
        migrations.AlterField(
            model_name='selllisting',
            name='for_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Item'),
        ),
    ]
