# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20160901_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='crafting_profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
