# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_auto_20160901_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
