# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_item_vendor_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-crafting_profit']},
        ),
    ]
