# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_auto_20160905_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-delayed_crafting_profit']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='crafting_profit',
            new_name='delayed_crafting_profit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='fast_crafting_profit',
            field=models.IntegerField(default=0),
        ),
    ]
