# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_auto_20160905_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicsForItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_change_count', models.PositiveIntegerField(default=0)),
                ('buy_sell_difference', models.PositiveIntegerField(default=0)),
                ('for_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.Item')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicsForRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limited_production', models.BooleanField(default=False)),
                ('ingredient_cost', models.PositiveIntegerField(default=0)),
                ('fast_crafting_profit', models.IntegerField(default=0)),
                ('delayed_crafting_profit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='delayed_crafting_profit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fast_crafting_profit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_cost',
        ),
        migrations.AddField(
            model_name='economicsforrecipe',
            name='for_recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.Recipe'),
        ),
    ]
