# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_auto_20160909_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_be_crafted',
            field=models.BooleanField(default=False),
        ),
    ]
