# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_item_can_be_crafted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='economicsforitem',
            old_name='buy_sell_difference',
            new_name='relist_profit',
        ),
    ]
